[package]
name = "app"
edition.workspace = true
version.workspace = true

[dependencies]
domain = { path = "../domain" }
async-trait = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
